# Generated by Django 3.2.10 on 2021-12-10 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_public', models.BooleanField()),
                ('join_code', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('rem_rounds', models.IntegerField(default=13)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ones', models.IntegerField(null=True)),
                ('twos', models.IntegerField(null=True)),
                ('threes', models.IntegerField(null=True)),
                ('fours', models.IntegerField(null=True)),
                ('fives', models.IntegerField(null=True)),
                ('sixes', models.IntegerField(null=True)),
                ('three_oak', models.IntegerField(null=True)),
                ('four_oak', models.IntegerField(null=True)),
                ('full_house', models.IntegerField(null=True)),
                ('small_straight', models.IntegerField(null=True)),
                ('large_straight', models.IntegerField(null=True)),
                ('yahtzee', models.IntegerField(null=True)),
                ('yahtzee_Flag', models.BooleanField(default=False)),
                ('bonus_Yahtzees', models.IntegerField(default=0)),
                ('upper_bonus', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.IntegerField(default=6)),
                ('d2', models.IntegerField(default=6)),
                ('d3', models.IntegerField(default=6)),
                ('d4', models.IntegerField(default=6)),
                ('d5', models.IntegerField(default=6)),
                ('roll_count', models.IntegerField(default=3)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
