# Generated by Django 3.2.10 on 2021-12-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='d1',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d2',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d3',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d4',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d5',
            field=models.IntegerField(default=6),
        ),
    ]
