# Generated by Django 4.0 on 2021-12-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_game_rem_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rem_rounds',
            field=models.IntegerField(default=13),
        ),
    ]
