# Generated by Django 3.2.10 on 2021-12-10 20:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20211209_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='d1',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='d2',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='d3',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='d4',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='d5',
        ),
        migrations.AddField(
            model_name='game',
            name='rem_rounds',
            field=models.IntegerField(default=13),
        ),
        migrations.AddField(
            model_name='hand',
            name='dice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=6, size=5),
        ),
        migrations.AddField(
            model_name='hand',
            name='roll_count',
            field=models.IntegerField(default=3),
        ),
    ]
