# Generated by Django 3.2.10 on 2021-12-11 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='join_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
