# Generated by Django 3.2.10 on 2021-12-10 20:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20211210_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='dice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=5),
        ),
    ]
