# Generated by Django 3.2.10 on 2021-12-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20211216_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='d2',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d4',
            field=models.IntegerField(default=4),
        ),
    ]
