# Generated by Django 3.2.6 on 2021-12-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_game_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
