# Generated by Django 4.0 on 2021-12-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_game_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='roll_count',
        ),
    ]
