# Generated by Django 3.2.7 on 2021-12-04 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0005_game_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ones', models.IntegerField(max_length=10, null=True)),
                ('twos', models.IntegerField(max_length=10, null=True)),
                ('threes', models.IntegerField(max_length=10, null=True)),
                ('fours', models.IntegerField(max_length=10, null=True)),
                ('fives', models.IntegerField(max_length=10, null=True)),
                ('sixes', models.IntegerField(max_length=10, null=True)),
                ('three_oak', models.IntegerField(max_length=10, null=True)),
                ('four_oak', models.IntegerField(max_length=10, null=True)),
                ('full_house', models.IntegerField(max_length=10, null=True)),
                ('small_straight', models.IntegerField(max_length=10, null=True)),
                ('large_straight', models.IntegerField(max_length=10, null=True)),
                ('yahtzee', models.IntegerField(max_length=10, null=True)),
                ('yahtzee_Flag', models.BooleanField(default=False)),
                ('bonus_Yahtzees', models.IntegerField(default=0, max_length=10)),
                ('upper_bonus', models.IntegerField(default=0, max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
