# Generated by Django 3.2.7 on 2021-12-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='bonus_Yahtzees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hand',
            name='fives',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='four_oak',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='fours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='full_house',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='large_straight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='ones',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='sixes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='small_straight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='three_oak',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='threes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='twos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='upper_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hand',
            name='yahtzee',
            field=models.IntegerField(null=True),
        ),
    ]
