# Generated by Django 4.0 on 2021-12-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20211216_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='d1',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d2',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d4',
            field=models.IntegerField(default=2),
        ),
    ]
