# Generated by Django 3.2.6 on 2021-12-07 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0007_auto_20211204_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand',
            old_name='fives',
            new_name='d1',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='four_oak',
            new_name='d2',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='fours',
            new_name='d3',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='full_house',
            new_name='d4',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='large_straight',
            new_name='d5',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='bonus_Yahtzees',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='ones',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='sixes',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='small_straight',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='three_oak',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='threes',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='twos',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='upper_bonus',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='yahtzee',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='yahtzee_Flag',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ones', models.IntegerField(null=True)),
                ('twos', models.IntegerField(null=True)),
                ('threes', models.IntegerField(null=True)),
                ('fours', models.IntegerField(null=True)),
                ('fives', models.IntegerField(null=True)),
                ('sixes', models.IntegerField(null=True)),
                ('three_oak', models.IntegerField(null=True)),
                ('four_oak', models.IntegerField(null=True)),
                ('full_house', models.IntegerField(null=True)),
                ('small_straight', models.IntegerField(null=True)),
                ('large_straight', models.IntegerField(null=True)),
                ('yahtzee', models.IntegerField(null=True)),
                ('yahtzee_Flag', models.BooleanField(default=False)),
                ('bonus_Yahtzees', models.IntegerField(default=0)),
                ('upper_bonus', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
