# Generated by Django 3.2.10 on 2021-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20211216_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='d3',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d4',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='hand',
            name='d5',
            field=models.IntegerField(default=5),
        ),
    ]
